package com.ieltsmastermind.practice.content.management.domain.enums;

public enum PracticeQuestionType {

    MULTIPLE_CHOICE,
    MATCHING,
    PLAN_LABELLING,
    MAP_LABELLING,
    DIAGRAM_LABELLING,
    FORM_COMPLETION,
    NOTE_COMPLETION,
    TABLE_COMPLETION,
    FLOW_CHART_COMPLETION,
    SUMMARY_COMPLETION,
    SENTENCE_COMPLETION,
    SHORT_ANSWER_QUESTIONS,

    IDENTIFYING_INFORMATION_TRUE_FALSE_NOT_GIVEN,
    IDENTIFYING_WRITERS_VIEWS_CLAIMS_YES_NO_NOT_GIVEN,
    MATCHING_INFORMATION,
    MATCHING_HEADINGS,
    MATCHING_FEATURES,
    MATCHING_SENTENCE_ENDINGS,
    DIAGRAM_LABEL_COMPLETION

}